In [3]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# ==========================================
# 1. JOUW DATA INLEZEN
# ==========================================

df = pd.read_csv(
    "/Users/mirtebatema/Desktop/TIL_2026/programming/opdracht/laadpunten_inkomen_per_gemeente.csv",
    sep=None,
    engine="python"
)

display(df.head())

# Alleen relevante kolommen
data = df[
    ["gemeente", "laadpunten_per_1000_huishoudens"]
].copy()

display(data.head())


# ==========================================
# 2. LANDKAART MET GEMEENTEGRENZEN INLEZEN
# ==========================================

gemeenten = gpd.read_file(
    "gemeentegrenzen.geojson"
)

display(gemeenten.head())
print(gemeenten.columns)


# ==========================================
# 3. DATA KOPPELEN AAN DE LANDKAART
# ==========================================

kaart = gemeenten.merge(
    data,
    left_on="gemeentenaam",   # naam van gemeente in GeoJSON
    right_on="gemeente",
    how="left"
)


# ==========================================
# 4. KAART MAKEN
# ==========================================

fig, ax = plt.subplots(figsize=(10, 12))

kaart.plot(
    column="laadpunten_per_1000_huishoudens",
    cmap="Blues",
    linewidth=0.3,
    edgecolor="white",
    legend=True,
    ax=ax,
    missing_kwds={
        "color": "lightgrey",
        "label": "Geen data"
    }
)

ax.set_title(
    "Aantal publieke laadpunten per 1.000 huishoudens",
    fontsize=16
)

ax.axis("off")

plt.tight_layout()
plt.show()

,gemeente,laadpunten_regulier_publiek,huishoudens,gem_gestandaardiseerd_inkomen_keur,med_gestandaardiseerd_inkomen_keur,gem_besteedbaar_inkomen_keur,med_besteedbaar_inkomen_keur,laadpunten_per_1000_huishoudens
0,'s-Hertogenbosch,1817,75500,44.3,38.0,62.9,49.0,24.07
1,Aa en Hunze,89,11400,42.6,38.9,62.5,54.0,7.81
2,Aalsmeer,316,14200,52.1,40.0,77.4,56.2,22.25
3,Aalten,138,11700,40.5,36.4,60.3,50.4,11.79
4,Achtkarspelen,54,12000,36.3,33.7,54.0,46.3,4.50

           gemeente  laadpunten_per_1000_huishoudens
0  's-Hertogenbosch                            24.07
1       Aa en Hunze                             7.81
2          Aalsmeer                            22.25
3            Aalten                            11.79
4     Achtkarspelen                             4.50

DataSourceError: gemeentegrenzen.geojson: No such file or directory